"""initial schema

Revision ID: bcc1a6dbbad3
Revises: 
Create Date: 2026-09-23 23:59:53.824111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc1a6dbbad3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entry',
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_ref', sa.String(length=200), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('product_details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=True)
    op.create_table('provider',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.String(length=40), nullable=True),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('provider_model',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=False),
    sa.Column('resolved_version', sa.String(length=120), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('rpd', sa.Integer(), nullable=True),
    sa.Column('daily_budget', sa.Integer(), nullable=True),
    sa.Column('daily_reset_tz', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_id')
    )
    op.create_index(op.f('ix_provider_model_provider_id'), 'provider_model', ['provider_id'], unique=False)
    op.create_table('query_set',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sampling_config', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'version')
    )
    op.create_index(op.f('ix_query_set_brand_id'), 'query_set', ['brand_id'], unique=False)
    op.create_index(op.f('ix_query_set_content_hash'), 'query_set', ['content_hash'], unique=True)
    op.create_table('tracked_entity',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('SELF', 'COMPETITOR', 'DISCOVERED', name='entitykind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name', 'kind')
    )
    op.create_index(op.f('ix_tracked_entity_brand_id'), 'tracked_entity', ['brand_id'], unique=False)
    op.create_table('analysis_job',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('query_set_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PARTIAL', 'COMPLETED', 'FAILED', name='jobstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['query_set_id'], ['query_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_job_brand_id'), 'analysis_job', ['brand_id'], unique=False)
    op.create_index(op.f('ix_analysis_job_correlation_id'), 'analysis_job', ['correlation_id'], unique=True)
    op.create_index(op.f('ix_analysis_job_query_set_id'), 'analysis_job', ['query_set_id'], unique=False)
    op.create_table('provider_usage_ledger',
    sa.Column('provider_model_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('rate_limited', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('exhausted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exhausted_quota_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_model_id', 'usage_date')
    )
    op.create_index(op.f('ix_provider_usage_ledger_provider_model_id'), 'provider_usage_ledger', ['provider_model_id'], unique=False)
    op.create_table('query',
    sa.Column('query_set_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent_type', sa.String(length=80), nullable=False),
    sa.Column('is_brand_named', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['query_set_id'], ['query_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_query_set_id'), 'query', ['query_set_id'], unique=False)
    op.create_table('analysis_result',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('prominence', sa.Float(), nullable=True),
    sa.Column('share_of_voice', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=False),
    sa.Column('ci_high', sa.Float(), nullable=False),
    sa.Column('breakdown_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_result_job_id'), 'analysis_result', ['job_id'], unique=True)
    op.create_table('collection_task',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('provider_model_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCEEDED', 'FAILED_TERMINAL', name='taskstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_job.id'], ),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_model.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['query.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'provider_model_id', 'query_id', 'sample_index')
    )
    op.create_index(op.f('ix_collection_task_job_id'), 'collection_task', ['job_id'], unique=False)
    op.create_index(op.f('ix_collection_task_provider_model_id'), 'collection_task', ['provider_model_id'], unique=False)
    op.create_index(op.f('ix_collection_task_query_id'), 'collection_task', ['query_id'], unique=False)
    op.create_table('gap',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('gap_type', sa.Enum('PRESENCE', 'PROMINENCE', 'REPRESENTATION', 'COMPETITIVE', 'SOURCE', name='gaptype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('is_inferred', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_content_hash'), 'gap', ['content_hash'], unique=True)
    op.create_index(op.f('ix_gap_job_id'), 'gap', ['job_id'], unique=False)
    op.create_table('raw_observation',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('provider_model_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OK', 'FAILED', name='observationstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=120), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('raw_meta', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_job.id'], ),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_model.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['query.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'provider_model_id', 'query_id', 'sample_index')
    )
    op.create_index(op.f('ix_raw_observation_job_id'), 'raw_observation', ['job_id'], unique=False)
    op.create_index(op.f('ix_raw_observation_provider_model_id'), 'raw_observation', ['provider_model_id'], unique=False)
    op.create_index(op.f('ix_raw_observation_query_id'), 'raw_observation', ['query_id'], unique=False)
    op.create_table('tracking_snapshot',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('comparability_key', sa.String(length=80), nullable=False),
    sa.Column('query_set_content_hash', sa.String(length=80), nullable=False),
    sa.Column('model_fingerprint', sa.String(length=80), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=False),
    sa.Column('ci_high', sa.Float(), nullable=False),
    sa.Column('breakdown_json', sa.JSON(), nullable=False),
    sa.Column('admission_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETE', 'PARTIAL', name='snapshotstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_snapshot_brand_id'), 'tracking_snapshot', ['brand_id'], unique=False)
    op.create_index(op.f('ix_tracking_snapshot_comparability_key'), 'tracking_snapshot', ['comparability_key'], unique=False)
    op.create_index(op.f('ix_tracking_snapshot_job_id'), 'tracking_snapshot', ['job_id'], unique=False)
    op.create_table('entity_mention',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('is_passing_mention', sa.Boolean(), nullable=False),
    sa.Column('prominence_band', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['tracked_entity.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['raw_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_mention_entity_id'), 'entity_mention', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_mention_observation_id'), 'entity_mention', ['observation_id'], unique=False)
    op.create_table('observed_only',
    sa.Column('gap_id', sa.Integer(), nullable=False),
    sa.Column('gap_type', sa.Enum('PRESENCE', 'PROMINENCE', 'REPRESENTATION', 'COMPETITIVE', 'SOURCE', name='gaptype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('decision_status', sa.Enum('OBSERVED_ONLY', name='observedonlystatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['gap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observed_only_gap_id'), 'observed_only', ['gap_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('gap_id', sa.Integer(), nullable=False),
    sa.Column('gap_type', sa.Enum('PRESENCE', 'PROMINENCE', 'REPRESENTATION', 'COMPETITIVE', 'SOURCE', name='gaptype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('action_class', sa.Enum('CONTENT', 'MESSAGING', 'DISTRIBUTION', name='actionclass', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('delta_composite', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('effort_constant', sa.Float(), nullable=False),
    sa.Column('closure_assumption_json', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('decision_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SAVED', name='decisionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('narrated_by_llm', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['gap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_content_hash'), 'recommendation', ['content_hash'], unique=True)
    op.create_index(op.f('ix_recommendation_gap_id'), 'recommendation', ['gap_id'], unique=False)
    op.create_table('distribution_event',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_event_recommendation_id'), 'distribution_event', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_event_recommendation_id'), table_name='distribution_event')
    op.drop_table('distribution_event')
    op.drop_index(op.f('ix_recommendation_gap_id'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_content_hash'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_observed_only_gap_id'), table_name='observed_only')
    op.drop_table('observed_only')
    op.drop_index(op.f('ix_entity_mention_observation_id'), table_name='entity_mention')
    op.drop_index(op.f('ix_entity_mention_entity_id'), table_name='entity_mention')
    op.drop_table('entity_mention')
    op.drop_index(op.f('ix_tracking_snapshot_job_id'), table_name='tracking_snapshot')
    op.drop_index(op.f('ix_tracking_snapshot_comparability_key'), table_name='tracking_snapshot')
    op.drop_index(op.f('ix_tracking_snapshot_brand_id'), table_name='tracking_snapshot')
    op.drop_table('tracking_snapshot')
    op.drop_index(op.f('ix_raw_observation_query_id'), table_name='raw_observation')
    op.drop_index(op.f('ix_raw_observation_provider_model_id'), table_name='raw_observation')
    op.drop_index(op.f('ix_raw_observation_job_id'), table_name='raw_observation')
    op.drop_table('raw_observation')
    op.drop_index(op.f('ix_gap_job_id'), table_name='gap')
    op.drop_index(op.f('ix_gap_content_hash'), table_name='gap')
    op.drop_table('gap')
    op.drop_index(op.f('ix_collection_task_query_id'), table_name='collection_task')
    op.drop_index(op.f('ix_collection_task_provider_model_id'), table_name='collection_task')
    op.drop_index(op.f('ix_collection_task_job_id'), table_name='collection_task')
    op.drop_table('collection_task')
    op.drop_index(op.f('ix_analysis_result_job_id'), table_name='analysis_result')
    op.drop_table('analysis_result')
    op.drop_index(op.f('ix_query_query_set_id'), table_name='query')
    op.drop_table('query')
    op.drop_index(op.f('ix_provider_usage_ledger_provider_model_id'), table_name='provider_usage_ledger')
    op.drop_table('provider_usage_ledger')
    op.drop_index(op.f('ix_analysis_job_query_set_id'), table_name='analysis_job')
    op.drop_index(op.f('ix_analysis_job_correlation_id'), table_name='analysis_job')
    op.drop_index(op.f('ix_analysis_job_brand_id'), table_name='analysis_job')
    op.drop_table('analysis_job')
    op.drop_index(op.f('ix_tracked_entity_brand_id'), table_name='tracked_entity')
    op.drop_table('tracked_entity')
    op.drop_index(op.f('ix_query_set_content_hash'), table_name='query_set')
    op.drop_index(op.f('ix_query_set_brand_id'), table_name='query_set')
    op.drop_table('query_set')
    op.drop_index(op.f('ix_provider_model_provider_id'), table_name='provider_model')
    op.drop_table('provider_model')
    op.drop_table('provider')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_table('brand')
    op.drop_table('audit_log_entry')
    # ### end Alembic commands ###
